### ISSUE TITLE
Change the license

### ISSUE THREAD

**Issue by vanillajonathan** [GeopJr/Hashbrown#10]
Consider changing the license from the AGPL to the GPL.

The AGPL is for hosted software such as web applications offered as software-as-a-service. It makes little sense for a desktop application.

Most GNOME software seem to use the GPL license.

**Comment by vanillajonathan** [comment]
IANAL either.

My understanding is that AGPL is modified in such a way that it extends the freedoms (the rights to the source code) to the user who interacts with the application even if the interaction is done over the network and the application is hosted elsewhere than on the user's own machine.

I think it is a bit uncommon to use the AGPL in a desktop application, I don't think the license was intended for that. I proposed the GPL since the AGPL is modified from the GPL and since the GPL seems rather commonly used by applications in the GNOME Project. You could use an even more permissive license though, such as the LGPL, MIT, ISC, or 2-clause BSD.

Since this project does not have any Contributor License Agreement (CLA), I believe you would have to get permission from everyone who have made non-trivial contributions to the project.

https://softwareengineering.stackexchange.com/questions/55326/can-you-change-a-license-once-you-pick-one

**Comment by GeopJr** [comment]
Thanks for the info!

For now however, I'll probably stick with AGPL. I understand that it's uncommon for non-SaaS and especially useless for Hashbrown, but changing it would be tedious right now.

I will revisit this issue after #7 and make a final decision, unless Hashbrown being AGPL licensed causes problems to someone's workflow, which will make me act sooner.

As of now, all contributions have been translations so there shouldn't be too much of an issue switching (at least on that part).

Once again, thanks for raising this issue, but for now it's marked as "stalled". I'll add it to my to-do list but feel free to leave this issue open.

P.S. I'm sure you are aware already, but in the off-chance you aren't, being in GNOME Circle != being a GNOME project. The difference is being an app **for** GNOME vs being an app **by** GNOME. There are some requirements Hashbrown has to follow (like not having a CLA and having an OSI-Approved license) however following GNOME's usuals(?) (Eg. Licenses, languages, translation systems etc.) Is not one of them. (Not that there's anything wrong with them, they are quite great!)

**Comment by vanillajonathan** [comment]
Sounds good! 👍️
Keep in mind though that changing the license is a thing best done sooner rather than later, as it gets more tedious as the number of contributors goes up.
