### ISSUE TITLE
Better summary

### ISSUE THREAD

**Issue by bertob** [GeopJr/Hashbrown#11]
The current summary "Generate, compare and verify MD5, SHA-256 & SHA-1 hashes" is not great (too long, too much technical detail, not very engaging).

I'd recommend something shorter and more practical, e.g. "Check hashes for downloaded files".

More general guidance here: https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/App-Metadata

**Comment by GeopJr** [comment]
Thanks for raising this issue!

You are absolutely right about the summary!
"Check hashes for downloaded files" sounds good, however I'm not sure if "downloaded" is *too* specific.
Would "Check hashes for **your** files" work? (Doesn't seem to not-follow the guidelines but any opinions on it would be appreciated :) )

**Comment by bertob** [comment]
> Check hashes for your files

Sounds good to me!
