### ISSUE TITLE
Sha512sum Support?

### ISSUE THREAD

**Issue by Scotty-Trees** [GeopJr/Hashbrown#15]
Greetings Hashbrown Dev(s),

Great little piece of software you got here! Looks very promising indeed and I really dig the name too. I'm currently using EndeavourOS Gnome 40.4 and while it is rolling release, I do tend to download their .iso every so often to test in a Boxes VM usually to help troubleshoot things for new users. Now admittedly I'm not an expert in all the different type of hash/sum/etc types so this question might be irrelevant/redundant, but to check the EndeavourOS .iso they use Sha512sum, which as far as I can tell Hashbrown doesn't offer support for it. 

So I'm curious to know if it's possible to eventually include that support in a later release or if it's not something that's on the devs road-map, please let me know. If you're curious to see the EndeavourOS .iso and Sha512sum, you may find it here halfway down the page: https://endeavouros.com/latest-release/

**Comment by GeopJr** [comment]
Thanks for raising this issue!

Will for sure add it when #7 is done!

**Comment by Scotty-Trees** [comment]
Awesome, sounds good to me, thank you!
