### ISSUE TITLE
Application freezes when opening big files

### ISSUE THREAD

**Issue by pesader** [GeopJr/Hashbrown#37]
**Describe the bug**
When uploading a big file (2Gb or more) to Hashbrown, it freezes and requires a "Force Quit" to be closed.

**To Reproduce**
1. Get ahold of a big file. I used Fedora Silverblue's and GNOME OS Nightly's iso files.
2. Open the big file on Hashbrown
3. Wait for it to freeze

**Expected behavior**
The app should not freeze with big files. My intended use for this app was verifying the checksums of iso files, which are typically huge.

**Screenshots**
![image](https://user-images.githubusercontent.com/65264536/149849725-63b2d96a-dd67-429a-a0a8-d52f3a630ca8.png)

**Environment (please complete the following information):**
 - OS: Fedora Silverblue 35
 - Install method: Flathub

**Comment by GeopJr** [comment]
Thanks for raising this issue!

I've been aware of this for quite some time and a fix is on the way! In the meantime, as a workaround, clicking "Wait" (or clicking nothing at all) should eventually show the hashes.

(Info on this issue: hash calculation are currently blocking the main thread/fiber).

**Comment by pesader** [comment]
Thank YOU for developing this awesome tool :)

And you are right, simply waiting will lead to hashes!
