### ISSUE TITLE
build error - libadwaita was not found in git

### ISSUE THREAD

**Issue by muralikodali** [GeopJr/Hashbrown#40]
building from source giving following error : 
```
Locked version 1.0.0+git.commit.f96452f91780b356e5c33f2e48567920b8eac5b8 for libadwaita was not found in git: https://github.com/geopjr/libadwaita.cr.git
```

**Comment by GeopJr** [comment]
Thanks for raising this issue!

It should be fixed as of 38a9f0b0fe5431e366ae3513a65c07006344533b

Unfortunately, I can't promise that it won't break again until next release as there will probably be more force pushes over at [libadwaita.cr](https://github.com/GeopJr/libadwaita.cr). (I'll try not to).
