### ISSUE TITLE
Merge Chinese translation

### ISSUE THREAD

**Issue by lumingzh** [GeopJr/Hashbrown#41]
Hi, I have translated Hashbrown to Simplified Chinese, please merge it.

Thank you.

**Comment by GeopJr** [comment]
Thanks for raising this issue!

I'm currently in the process of moving to [gettext](https://github.com/GeopJr/gettext.cr), so translations will be imported (and converted) after that's done!

I'll leave this issue open until then.

**Comment by GeopJr** [comment]
Done as of 167335e97c4db3a484cb9d43df04a5b813084d27!

Thanks for raising this issue!
