### ISSUE TITLE
Move translation to weblate or damned lies

### ISSUE THREAD

**Issue by lumingzh** [GeopJr/Hashbrown#42]
[weblate.org](https://weblate.org) has some great features that poeditor missing, and it's open source. I think it's better to using weblate for translation instead of poeditor.

And as GNOME circle app, [damned lies](https://l10n.gnome.org/) of gnome is another good choice.

Thank you.

**Comment by GeopJr** [comment]
Thanks for raising this issue!

I was avoiding using those services as the current translation system(?) is not that standard and would probably cause some uneeded issues to them. As mentioned in the other issue, I'm currently in the process of moving to Gettext, after that's done, I'll look into migrating to another service!

**Comment by GeopJr** [comment]
Done as of c4342c918e1f7a23ef3d2fceb53c729faf286068!

Hashbrown/Collision moved to gettext & Weblate: https://hosted.weblate.org/engage/collision/

Thanks for raising this issue!
