### ISSUE TITLE
Follow-up from discussion

### ISSUE THREAD

**Issue by comradekingu** [GeopJr/Hashbrown#47]
https://github.com/GeopJr/Hashbrown/pull/46 got closed just as I pressed submit:
(happy to move it there if it is unlocked)

@Jonohas
I understand you could wish to shut down debate that way, or somehow deprive us of the logic behind our actions in so doing.
So far there is no such saving grace available.

@n0toose I agree a flirt can fail and that it is no big issue.
The difference between what must be a course of engagement for that to happen and "sexual attention or advances of any kind" being "unacceptable" is that the former is impossible if the latter is implemented. That isn't interpretative. 
No jurisdiction employs personal perception as harassment, because it is ungovernable. The fabric of trust and the model of society erodes at that point, and in place you have ultimate authority in wielded and unnegotiated power.
If you don't think it exists as a word with meaning, why do you suppose it is there? It is re-defined.

A _vested_ interest means sunken cost. Represented in the merit-part of _meritocracy_. As far as a fruitful project goes, it is a demonstration of ability.
To offer that is worth something. To me it represents my values, and authoritarianism does not.
That this is a smaller project doesn't mean it doesn't belong to a greater ecosystem.
I like it, and I am offering my contributions on the premise of not misrepresenting its values as far as I am concerned, and we agree there.
If you want to stop caring then that is fine by me, but it doesn't answer the problem I have.

As I have gone to such extents as to actually read the text-file, it isn't even just gain of power as it shifts, but actually a responsibility. The CoC places itself atop all else in this matter.

> responsibility to remove, edit, or reject
comments, commits, code, wiki edits, issues, and other contributions that are
not aligned to this Code of Conduct, 

Armed with interpretation of the vaguest of rationales possible, with total power and no oversight, do we get any reasoning for giving it all up, retroactively?
>… and will communicate reasons for moderation decisions when appropriate.

I am not proposing that someone with ulterior political motives or anti-social proclivities are likely to enter this project anytime soon. What I am saying is that this happens because it is made possible.
I don't think the text-file is good, because when you bring up what it says, it differs completely from what people say it contains.

**Comment by GeopJr** [comment]
Previous issue got locked for a reason. Move to forums or literally anywhere else to continue this debate.
