### ISSUE TITLE
GTK 4, libadwaita, new HIG

### ISSUE THREAD

**Issue by GeopJr** [GeopJr/Hashbrown#7]
Hashbrown should switch to GTK 4, use libadwaita and comply with the new HIG.

Currently [`crystal-gobject`](https://github.com/jhass/crystal-gobject) supports only GTK 3. However there's a promising lib for [`gtk4`](https://github.com/hugopl/gtk4.cr) available but as the readme mentions, it's not ready yet.

There were some attempts to use libhandy (some [public](https://github.com/GeopJr/Hashbrown/tree/libhandy) some local) but since GTK 4 is here, it might be better to postpone them until there's stable support (for both gtk4 and libadwaita) in Crystal.

In regards of the new HIG, the plan is to:

- Move the from `GtkStackSwitcher` to `AdwViewSwitcher` (+ `AdwViewSwitcherTitle` & `AdwViewSwitcherBar`) with Title and Bar toggling dynamically based on window size.
- Move to `AdwApplicationWindow`
- Wrap labels and other widgets to support a wider variety of window sizes
- Use `GtkListBox` + rows instead of grids & boxes
- `GtkPopoverMenu`

(More items might be added to the above list)

**Comment by genodeftest** [comment]
> Hashbrown should switch to GTK 4, use libadwaita and comply with the new HIG.

Maybe not yet because there is a major issue with gtk4 which renders it pretty hard to use for people with non-HiDPI monitors: https://gitlab.gnome.org/GNOME/gtk/-/issues/3787

**Comment by GeopJr** [comment]
I'm sure that issue will be fixed by the time a gtk4 (+ libadwaita) library for Crystal becomes ready, thanks however for bringing it to my attention!
